name: Deployment

on:
  push:
    branches:
      - main
  # pull_request:
  #   branches:
  #     - main
jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region "ap-southeast-2"

      - name: Deploy index to s3
        run: aws s3 cp ./index.html s3://synth-stage-static-page/index.html
